//======================== flak_io_codes.h =======================//
#define IOCTL_SETAKHOOK 	CTL_CODE( FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS ) 
#define IOCTL_RELEASEAKHOOK 	CTL_CODE( FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS ) 
#define IOCTL_ADDPROCESSID 	CTL_CODE( FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS ) 
#define IOCTL_REMPROCESSID 	CTL_CODE( FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS ) 
#define IOCTL_GETPROCESSIDLIST 	CTL_CODE( FILE_DEVICE_UNKNOWN, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS ) 
